// Events
const ADD_COMPONENT = 'ADD_COMPONENT';
const SORT_ROW = 'SORT_ROW';
const UPDATE_ROW = 'UPDATE_ROW';
const DUPLICATE_ROW = 'DUPLICATE_ROW';

export { ADD_COMPONENT, SORT_ROW, UPDATE_ROW, DUPLICATE_ROW };
