// Events
const ADD_COMPONENT = 'ADD_COMPONENT';
const SORT_ROW = 'SORT_ROW';
const UPDATE_ROW = 'UPDATE_ROW';
const DUPLICATE_ROW = 'DUPLICATE_ROW';
const DELETE_ROW = 'DELETE_ROW';
const ADD_COMPONENT_WITH_DRAG_DROP = 'ADD_COMPONENT_WITH_DRAG_DROP';

export {
  ADD_COMPONENT,
  ADD_COMPONENT_WITH_DRAG_DROP,
  SORT_ROW,
  UPDATE_ROW,
  DUPLICATE_ROW,
  DELETE_ROW
};
